FROM nginx:alpine-slim
ARG           name_a_build_arg
RUN echo "Hi $name_a_build_arg!" > /usr/share/nginx/html/'index.html'
#CMD LUU Y minh ne' khong thaydoi CMD de nginx chay lenh cua no phucvu web server  #TODO thaydoi CMD va goi lai entrypoint cu~
