#ref https://chatgpt.com/share/e/6965bfec-0fcc-800b-9fb7-081d75c1c231
FROM python:3.12-alpine
CMD ["python", "-c", "import calendar; from datetime import datetime; now=datetime.now(); print(calendar.month(now.year, now.month))"]
